# Generated by Django 2.2.3 on 2019-09-04 16:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('all_books', '0006_book_publications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 4, 16, 37, 27, 338120, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
