# Generated by Django 2.2.3 on 2019-09-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_books', '0007_auto_20190904_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='return_date',
            field=models.DateTimeField(null=True),
        ),
    ]
